In [1]:
import numpy as np

### Массив из обычного списка

In [3]:
my_list = [1, 2, 3, 4, 5] # исходный список
my_array = np.array(my_list) #создание массива
print(my_array)


[1 2 3 4 5]


### Двумерный массив

In [7]:
list_2 = [[1,2,3],[4,5,6],[7,8,9]] # создаем двумерный список
array_2 = np.array(list_2)
print(array_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### С использованием функций

In [16]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 6)
d = np.arange(10, 20)
print(a)
print(b)
print(c)
print(d)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[6 6 6 6 6 6 6 6 6 6]
[10 11 12 13 14 15 16 17 18 19]


### Демонстрация атрибутов

In [23]:
x = np.arange(25).reshape(5,5) # создаем матрицу со значениями от 0 до 24, размерность 5 на 5
print(x)
print(x.shape)
print(x.dtype)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)
int32


### Примеры индексирования и срезов

In [35]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]]) # создаем двумерный массив 4 на 5
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### Получение отдельного элемента

In [42]:
print(arr[1,2]) # элемент во второй строке, третьем столбце (индексация с 0)
print(arr[3,0]) # элемент в 4 строке, первом столбце
print(arr[-1,-1]) # элемент в послединй строке, последнем столбце

8
16
20


### Извлечение подмассивов с помощью срезов

In [53]:
print("Первые две строки:")
print(arr[:2])

print("\nСтолбцы 1-3 (индексы 1,2,3):")
print(arr[:, 1:4])

print("\nКаждая вторая строка и столбец:")
print(arr[::2, ::2])

print("\nПоследние две строки, первые три столбца:")
print(arr[-2:, :3])

print("\nС шагом 2:")
print(arr[::2, ::2])

Первые две строки:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Столбцы 1-3 (индексы 1,2,3):
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]]

Каждая вторая строка и столбец:
[[ 1  3  5]
 [11 13 15]]

Последние две строки, первые три столбца:
[[11 12 13]
 [16 17 18]]

С шагом 2:
[[ 1  3  5]
 [11 13 15]]


### Примеры векторных операций и базовых статистик 

In [58]:
a = np.array([1,2,3,4,5])
b = np.array([2,2,1,3,4])

print(f"\nПоэлементное сложение: {a + b}")

print(f"\nПоэлементное умножение: {a * b}")



Поэлементное сложение: [3 4 4 7 9]

Поэлементное умножение: [ 2  4  3 12 20]


### Вычисление средней величины

In [67]:
data = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10],
                 [11, 12, 13, 14, 15]])
print(data) # основной массив

print(np.mean(data)) # cреднее массива

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
8.0
